# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdb332df3ff4bb9256e160da98eceae9c7d1489758ae8d7a80fffb0834c4215246d9557f22d65352b61df7a9149595e09a300c1c8f5e764cfe636034a1bea784

test:
  secret_key_base: da0543c1fdd713aa5b3ceafc7f20b612e0cb48472d5f4bbfbac83e3062e9ed887f92fcd8de82d39bd12fcfd7479eb39f3e6aeaa41c0b640076f6147c1bf68716

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
